[appservers]
myserver ansible_host=144.31.187.246 ansible_user=root

[dbservers]
myserver ansible_host=144.31.187.246 ansible_user=root
[redis_hosts]
myserver ansible_host=144.31.187.246 ansible_user=root
